design: backend TLS with client certificate (#2338)
projectcontour/contour pull request #2848
Opened 2020-08-28 20:11 UTC by tsaarni

This proposal describes how to implement support for client certificate for Envoy for the TLS connection between Envoy and backend services.

This updates #2338

Signed-off-by: Tero Saarni <tero.saarni@est.tech>

2020-08-29 06:44 UTC, tsaarni commented
Adding the picture from the referred issue here to explain the use case also visually:

![76843389-63d21a80-6844-11ea-92db-f5396669c43f](https://user-images.githubusercontent.com/85464/91629680-bd359c80-e9d3-11ea-97d6-cddb6d45a1ce.png)

Here in this picture the logical end-to-end connection is split into two TLS connections. The cluster external green leg is already protected by mutual TLS authentication but due to missing client certificate the red leg is not.  Unauthorized client in red is able to connect the upstream server as long as this is true.

I had a few questions in my mind and I'd appreciate to hear your opinions:

**Q1:** Configure client cert as a global command line parameters vs HTTPProxy? 

Since from Envoy's perspective the client certificate is a parameter in the upstream cluster definition, each upstream could be configured with a different client certificate.  From that point of view, the parameters could be part of `HTTPProxy.spec.routes[].services[]` instead of being a global parameter.

**Q2:** Would the multitenancy perspective drive towards global vs per service client certificate?

From security perspective I consider all Envoys being single "distributed" TLS client, all equally authorized to connect to the upstream services.  Therefore single client certificate is enough for the use case. Separate certificates could be needed e.g. if upstream needs to tell each Envoy apart but I don't see that as valid use case. 

But what about multitenancy perspective?  I don't have experience in using Contour in multitenant way myself so I'd appreciate to hear how you see this from workflow / management perspective. For the TLS server validation, each team is able to manage the CA certificate with `HTTPProxy.spec.routes[].services[].validation` structure.  For symmetry: should client side be managed by individual teams as well?

- If yes, team manages both client and server certs.
- If not, team receives the CA certificate for validating Envoy's client certificate from the cluster admin.

**Q3:** Cluster internal TLS and certificate delegation?

Delegation is for wildcard certificates in cluster external TLS, but would this feature add another use case for delegation: If a client certificate would be configured per HTTPProxy, would users still want to refer to a single globally configured secret?

2020-09-01 05:33 UTC, youngnick commented
Thanks for this PR @tsaarni!

My initial read on your questions is:

I think that in general, the most used pattern will probably be that the Contour Envoys constitute a 'service' and should have a single identity most of the time.

To that end, a global setting is the place to start, with the ability to set a client certificate and a single CA. This should hit the more obvious use-cases, even for multitenancy. If users still need greater configurability, we can come back around and see if we grant the ability to override the default on a per-HTTPProxy basis.

However, I'm going to check the service-apis for how we will need to do this there, and see if there's anything we can crib back.

2020-09-01 08:06 UTC, jpeach requested changes
This looks great - cleanly scoped, solid use case and nicely written. I think that it would be good for posterity if you merge some of the FAQ items you discussed in the issue into the main doc.

2020-09-01 08:06 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +New optional argument is added to `contour serve` named `--envoy-client-certificate` which refers to a Secret.
Not sure that we need a flag. Shall we start with config-only and see how that goes?

2020-09-01 08:06 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +When client certificate is defined in Contour configuration, it can be added to all Envoy clusters regardless if it will be used or not.
When ExtensionClusters land, we should have the same feature for this too. Just need to mention that here, and make sure we have an issue for it when you scope the work.

2020-09-01 08:06 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +The reference contains the namespace and the Secret name e.g. `namespace/name`.
I think it's OK to not need a certificate delegation here since the certificate is being used by the infrastructure not by an application. Just add a note if you agree with this reasoning.

2020-09-01 19:24 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +The same configuration is added to the Contour configuration file in the optional `tls.envoy-client-certificate` location.
Added a note on following the same pattern.

2020-09-01 19:26 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +Note that since only single client certificate is supported, the secret is the same for all instances of type `dag.Cluster`.
I added chapter "Alternatives Considered" with per `HTTPProxy` ideas.

2020-09-01 19:40 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +When `CommonTlsContext` is constructed for the upstream connection, the client certificate is added using `SdsSecretConfig`, that is, the secret is streamed over SDS.
Do you mean CA bundle that the backend administrators/developers need for validating Envoy's client cert?

I think it would be outside of scope of this document. Since Contour or Envoy would not use it by itself, it would be up to the users to decide.  It could be well-known secret (assuming that backend admins have read access to to it) or it could be any out-of-band mechanism, like email.

I added mention about this in "Non Goals" chapter.

2020-09-01 19:42 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +Note that since only single client certificate is supported, the secret is the same for all instances of type `dag.Cluster`.
Yes, I added information on "Detailed Design".  This is how I assume xDS streaming works in Contour, and I hope this is not too far from truth, since I did not try this myself yet!

2020-09-01 19:43 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +New optional argument is added to `contour serve` named `--envoy-client-certificate` which refers to a Secret.
I removed the flag and just left the config.

2020-09-01 19:46 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +When client certificate is defined in Contour configuration, it can be added to all Envoy clusters regardless if it will be used or not.
I was not able to find any details on ExtensionClusters, is there anything out yet?

2020-09-01 19:57 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +The reference contains the namespace and the Secret name e.g. `namespace/name`.
I did not write anything about this one yet, since wouldn't certificate delegation become relevant only if user is allowed to configure client certs in `HTTPProxy`?  Delegation concept does not apply when there is single global parameter and no way for teams in multitenant cluster to impact that?

2020-09-01 20:10 UTC, tsaarni commented
> I think that it would be good for posterity if you merge some of the FAQ items you discussed in the issue into the main doc.

I added "Security Considerations" chapter with content from the discussions.

2020-09-02 00:37 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +When client certificate is defined in Contour configuration, it can be added to all Envoy clusters regardless if it will be used or not.
https://github.com/projectcontour/contour/blob/main/design/external-authorization-design.md

2020-09-02 00:47 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +When `CommonTlsContext` is constructed for the upstream connection, the client certificate is added using `SdsSecretConfig`, that is, the secret is streamed over SDS.
The reason we need the CA is so the TLS peer can chain the client certificate back to a trusted root. So I think that we should add the CA bundle if is it present in the secret, consistent with how we use the `ca.crt` field in other TLS secrets. I think that we can start without supporting CA bundles in a separate secret.

2020-09-02 01:28 UTC, jpeach commented
> **Q1:** Configure client cert as a global command line parameters vs HTTPProxy?

There's 3 possible options AFAICT
1. Certificate per Contour deployment
2. Certificate per Envoy proxy pod
3. Certificate per HTTPProxy service

Each of these options has slightly different properties. I'm inclined to view this as an infrastructure certificate, which means starting at (1) and maybe progressing to (2) in the future. Would be interested if there are use cases for (3).

> **Q2:** Would the multitenancy perspective drive towards global vs per service client certificate?

A Contour deployment is 1-1 with a fleet of Envoy proxies, so each Contour deployment would be for a tenant. I agree that a separate certificate for each deployment is OK.

We should check whether the Contour TLS certificate validation allows SPIFFE certificates (looks to me like it won't accept them).

> **Q3:** Cluster internal TLS and certificate delegation?

Delegation is where an application is granted access to secrets owned by a cluster operator. Since these secrets are never used by an application, I don't think delegation comes into play.

2020-09-02 01:28 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +The reference contains the namespace and the Secret name e.g. `namespace/name`.
Yep, just capture that reasoning in the doc.

2020-09-02 04:26 UTC, tsaarni commented
> There's 3 possible options AFAICT
> 
> 1. Certificate per Contour deployment
> 2. Certificate per Envoy proxy pod
> 3. Certificate per HTTPProxy service

When multitenancy is done by having isolated deployments (1) we of course have per deployment configuration (so in a sense it was wrong for me to say "global configuration").

I was also thinking (2) but it would require Contour to tell Envoys apart from each other.  Also, since Contour pushes all configuration to all Envoys, the instances would need to be equally authorized to connect to any backend.  Backend X should either allow connections from all Envoys within Contour deployment or none.  Last, the number of Envoys can change, which makes it challenging to manage the number of client certificates.  Therefore I was thinking it is not a valid use case - all Envoys are seen as single distributed TLS client with a single identity.

Multitenancy can be bit overloaded word.  When reading how it was used within Contour, I understood that it is used to refer to a cluster with single Contour deployment where several devops teams manage their own routes by `HTTPProxy` inclusions?  In this scenario, I imagine tenants would be within single organization, so this is not necessarily the most typical use of the word.  Following that thought, I was thinking that the teams might want to manage their certificates, including the client certificate at the Envoy side, and that this would be scenario (3): define per `HTTPProxy`. This would be symmetrical how they already now manage the CA certificates for validating server certificate for the backends they set up.

> We should check whether the Contour TLS certificate validation allows SPIFFE certificates (looks to me like it won't accept them).

Yeah, I agree. SPIFFE certs do not have common name and `validateCertificate()` will fail.

2020-09-02 04:41 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +When `CommonTlsContext` is constructed for the upstream connection, the client certificate is added using `SdsSecretConfig`, that is, the secret is streamed over SDS.
Ok got it!  I think the convention is to add chain certificates as additional PEM blocks to `tls.crt` which I now added to the design doc.  I believe `kubectl create secret tls` has not allowed add separate `ca.crt`bundle file for chain certs.

2020-09-02 04:42 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +When client certificate is defined in Contour configuration, it can be added to all Envoy clusters regardless if it will be used or not.
I've added note with reference to external auth doc in the "detailed design" chapter.

2020-09-02 04:42 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +The reference contains the namespace and the Secret name e.g. `namespace/name`.
Done.

2020-09-03 23:58 UTC, jpeach commented
> > We should check whether the Contour TLS certificate validation allows SPIFFE certificates (looks to me like it won't accept them).
> 
> Yeah, I agree. SPIFFE certs do not have common name and `validateCertificate()` will fail.

xref https://github.com/projectcontour/contour/issues/2883

2020-09-04 00:11 UTC, jpeach commented on design/tls-backend-client-authentication.md
> +When `CommonTlsContext` is constructed for the upstream connection, the client certificate is added using `SdsSecretConfig`, that is, the secret is streamed over SDS.
cert-manager secrets put the CA bundle in `ca.crt` so it's a pattern that's used in the wild. Not sure Contour deliberately supports placing the bundle in the `tls.crt` yep but it probably works too.

2020-09-04 00:11 UTC, jpeach approved these changes
This looks great to me.

2020-09-04 00:12 UTC, jpeach commented
@youngnick LMK if you have any further feedback. If not, I'll land this on Monday.

2020-09-06 23:34 UTC, youngnick approved these changes
This LGTM, with one small nit. Thanks again @tsaarni, great work!

2020-09-06 23:34 UTC, youngnick commented on design/tls-backend-client-authentication.md
> +Configurating the client certificate shall follow the same configuration pattern as `fallback-certificate`.
Nit: 
```suggestion
Configuring the client certificate shall follow the same configuration pattern as `fallback-certificate`.
```

2020-09-07 05:25 UTC, tsaarni commented on design/tls-backend-client-authentication.md
> +Configurating the client certificate shall follow the same configuration pattern as `fallback-certificate`.
Fixed!

2020-09-07 05:41 UTC, merged

2020-09-15 19:35 UTC, tsaarni commented
xref #2910