docs: Add Contour deprecation policy
projectcontour/contour pull request #2912
Opened 2020-09-16 08:06 UTC by youngnick

Fixes #2749

Signed-off-by: Nick Young <ynick@vmware.com>

2020-09-16 14:20 UTC, stevesloka requested changes
Also, how does code in here (https://github.com/projectcontour/contour/blob/main/apis/projectcontour/v1/helpers.go), for example, get deprecated / changed? It's not really part of an API version, but since public, changes can be breaking for users.

2020-09-16 14:20 UTC, stevesloka commented on site/_resources/deprecation-policy.md
> +Contour published a few APIs, the most notable being the `projectcontour.io` api group of Kubernetes objects, the command line for `contour`, and the Contour configuration file.
nit: s/published/publishes

2020-09-17 05:24 UTC, youngnick commented on site/_resources/deprecation-policy.md
> +Contour published a few APIs, the most notable being the `projectcontour.io` api group of Kubernetes objects, the command line for `contour`, and the Contour configuration file.
Fixed.

2020-09-17 05:27 UTC, youngnick commented
@stevesloka thanks for that. I've added some statements around the helper code.

2020-09-17 14:55 UTC, stevesloka approved these changes
The helpers in the API sections still feel like we're going to need to version stuff all the time when those change and they should't be there (at least the one's with business logic), but otherwise lgtm.

2020-09-17 20:02 UTC, skriss commented
> The helpers in the API sections still feel like we're going to need to version stuff all the time when those change and they should't be there (at least the one's with business logic), but otherwise lgtm.

Yeah, I hadn't really considered that when those helpers were added, but now that you bring it up, it'll certainly make me less inclined to add things in there so I don't have to maintain compatibility :)

2020-09-17 20:03 UTC, skriss approved these changes

2020-09-18 00:00 UTC, merged