Adds Contour Operator to Deployment Docs Page
projectcontour/contour pull request #3140
Opened 2020-11-19 00:46 UTC by danehans

Adds Contour Operator to Contour's deployment docs page.

Signed-off-by: Daneyon Hansen <daneyonhansen@gmail.com>

2020-11-25 06:56 UTC, youngnick commented
Could you rebase please @danehans ? I've fixed some CI problems on `main`, that should clear the failures on here.

2020-11-25 22:55 UTC, youngnick requested changes
Just a small thing about making sure we don't over-promote the operator until it's done.

2020-11-25 22:55 UTC, youngnick commented on site/docs/main/deploy-options.md
> +The [`contour` example][2] or [Contour Operator][12] will install this for you.
I'd like to see "the experimental" or similar here until the operator is GA.

2020-11-25 23:23 UTC, danehans commented
@youngnick commit `7c601c7` resolves https://github.com/projectcontour/contour/pull/3140#discussion_r530682748, PTAL.

2020-11-26 03:09 UTC, youngnick approved these changes

2020-11-26 03:33 UTC, merged