Update Service APIs references to Gateway APIs
projectcontour/contour pull request #3397
Opened 2021-02-23 22:45 UTC by youngnick

Signed-off-by: Nick Young <ynick@vmware.com>

2021-02-23 22:52 UTC, danehans commented
@youngnick nit: the project should be referenced in the singular tense (Gateway API) and not plural (Gateway APIs). I think it does make sense to state that Gateway API is a group or collection of APIs or resources so the reader understands that the project is not a single API.

2021-02-23 23:06 UTC, danehans approved these changes

2021-02-23 23:07 UTC, sunjayBhatia requested changes

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
> +The Gateway API are the evolution of the Kubernetes APIs that relate to `Services`, such as Ingress.
```suggestion
The Gateway API is the evolution of the Kubernetes APIs that relate to `Services`, such as Ingress.
```

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
> +The Gateway API are the evolution of the Kubernetes APIs that relate to `Services`, such as Ingress.
nit on tense (though the Gateway API docs do not follow the tense correctly 100% of the time)

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
> +In terms of the APIs themsleves, the Gateway API has 3 primary API resources (taken from the gateway-apis docs site):
```suggestion
In terms of the APIs themselves, the Gateway API has 3 primary API resources (taken from the gateway-apis docs site):
```

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
> +- Define a data model and implementation for Contour's gateway-apis support, covering the v1alpha1 version of the gateway-apis.
```suggestion
- Define a data model and implementation for Contour's Gateway API support, covering the v1alpha1 version of the Gateway API.
```

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
> +There are already internal fields in the cache to hold GatewayClass and some other gateway-apis objects.
```suggestion
There are already internal fields in the cache to hold GatewayClass and some other Gateway API objects.
```

2021-02-23 23:07 UTC, sunjayBhatia commented on design/gateway-apis-implementation.md
>  - Deprecate `--expermental-service-apis` command-line flag, so that it does nothing but log a referral to the new config item.
```suggestion
- Deprecate `--experimental-service-apis` command-line flag, so that it does nothing but log a referral to the new config item.
```

2021-02-24 00:03 UTC, sunjayBhatia approved these changes

2021-02-24 01:08 UTC, merged