Implement "Exact" HTTPHeaderMatch
projectcontour/contour pull request #3478
Opened 2021-03-14 06:00 UTC by nak3

This patch adds "Exact" HTTPHeaderMatch.

Fix https://github.com/projectcontour/contour/issues/3356

Signed-off-by: Kenjiro Nakayama <nakayamakenjiro@gmail.com>

/cc @stevesloka @youngnick

2021-03-15 13:58 UTC, stevesloka requested changes

2021-03-15 13:58 UTC, stevesloka commented on internal/dag/gatewayapi_processor.go
> +		var pathMatchConditaions []MatchCondition
nit: s/pathMatchConditaions/pathMatchConditions/g

2021-03-15 13:58 UTC, stevesloka commented on internal/dag/gatewayapi_processor.go
>  				p.Error("NOT IMPLEMENTED: Only PathMatchPrefix is currently implemented.")
Can we update this error message?

2021-03-15 14:04 UTC, sunjayBhatia reviewed
See also: https://github.com/projectcontour/contour/pull/3471 which does the same for ingress

there are some pieces in there that overlap with this change and are needed here, namely the sorting and other test changes

We should probably also add some integration testing to make sure this works end to end

2021-03-29 03:34 UTC, youngnick commented
@nak3, do you think you could check over #3471 and see if anything needs updating here?

2021-03-29 07:24 UTC, nak3 commented
Umm... It seems sorting are moved to https://github.com/projectcontour/contour/pull/3504. The sort dag is already called by gateway APIs builder or this PR needs to be changed for the sort dag? @sunjayBhatia

2021-03-29 15:24 UTC, sunjayBhatia commented
> Umm... It seems sorting are moved to #3504. The sort dag is already called by gateway APIs builder or this PR needs to be changed for the sort dag? @sunjayBhatia

Ah yeah forgot to update here when I pulled the sorting PR out as its own thing. You shouldn't need to change anything to accommodate sorting route matches in this PR, #3504 should take care of it and it was already merged.

2021-03-30 00:43 UTC, nak3 commented
Thank you!
Then I think this PR is ready now. cc @stevesloka @youngnick 
For e2e test, I think I should add it to contour-operator.

2021-03-30 20:31 UTC, stevesloka approved these changes

2021-04-01 03:31 UTC, nak3 commented
Rebased to solve confliction.

2021-04-02 14:03 UTC, sunjayBhatia commented
> Rebased to solve confliction.
Looks like a CI failure to check out

2021-04-02 14:37 UTC, nak3 commented
Sorry I missed it. Update it now. Thank you!

2021-04-05 14:53 UTC, sunjayBhatia approved these changes

2021-04-06 16:06 UTC, skriss reviewed
Thanks for this @nak3, the code LGTM. It would be great to also add some test cases for exact matching to `_integration/testsuite/gatewayapi/001-patch-condition-match.yaml`.

2021-04-07 11:45 UTC, nak3 commented
Sure, added integration test. Thank you!

2021-04-07 14:27 UTC, merged