test/e2e/ingress: Add test that ensures v1beta1 works
projectcontour/contour pull request #3629
Opened 2021-04-30 18:43 UTC by sunjayBhatia

Basic test to make sure v1beta1 Ingress resources continue to
work as we remove internal code that references v1beta1.

This test can be removed once we support k8s versions that remove
v1beta1.

Updates #3628

This is based on https://github.com/projectcontour/contour/pull/3622 initially as that adds the new e2e go framework

2021-04-30 19:38 UTC, skriss requested changes
@sunjayBhatia looks great! Just one suggestion on namespace naming, and ready for a rebase since I merged the initial PR.

2021-04-30 19:38 UTC, skriss commented on test/e2e/ingress/002_ensure_v1beta1_test.go
> +	namespace := "002-ensure-v1beta1"
like you've said previously we should move this into the framework somewhere, but for now would be nice to prefix as "002-ingress-..."

2021-05-03 14:49 UTC, skriss approved these changes

2021-05-06 19:27 UTC, stevesloka approved these changes
lgtm

This should stop working in k8s 1.22 right?

2021-05-06 19:29 UTC, sunjayBhatia commented
> lgtm
> 
> This should stop working in k8s 1.22 right?

yep, 1.22 this will stop working, I'm working on ripping out all the v1beta1 code right now

2021-05-06 19:39 UTC, merged