Do not ignore CA when downstream skip verify is true
projectcontour/contour pull request #3661
Opened 2021-05-10 21:01 UTC by sunjayBhatia

- if no CA set and skip verify is true, client certs are not required by
Envoy
- if CA set and skip verify is true, client certs are required by Envoy
- CA still required if skip verify is false

2021-05-10 21:52 UTC, skriss commented
This is probably worth some updated documentation, maybe in the API godoc for these fields and also in https://projectcontour.io/docs/main/config/tls-termination/#client-certificate-validation, since the behavior here might not be the most intuitive

2021-05-11 01:14 UTC, youngnick requested changes
The code looks good to me, but I think the documentation updates are a must-have.

2021-05-12 04:15 UTC, youngnick approved these changes
Doc updates look good, 👍

2021-05-13 14:03 UTC, skriss commented
You've got a merge conflict to resolve now

2021-05-13 14:06 UTC, skriss approved these changes

2021-05-13 15:18 UTC, sunjayBhatia commented
hold for merging until https://github.com/projectcontour/contour/pull/3665 is done, want to add to the integration test that is int that PR

2021-05-14 22:48 UTC, stevesloka commented
@sunjayBhatia looks like #3665 has merged so this is good to go. Also needs a rebase. =)

2021-05-17 19:21 UTC, sunjayBhatia commented
still having an issue with an integration test that I just added, not sure why the "accept untrusted" setting with a CA is not passing on a request that comes with certs from a different CA

2021-05-17 21:54 UTC, sunjayBhatia commented on test/e2e/httpproxy/007_client_cert_auth_test.go
> +		c.GetClientCertificate = func(*tls.CertificateRequestInfo) (*tls.Certificate, error) {
note this change, just commenting for visibility

2021-05-17 21:54 UTC, skriss commented on test/e2e/httpproxy/007_client_cert_auth_test.go
>  }
aha, 👍 figuring that out

2021-05-17 21:59 UTC, skriss approved these changes

2021-05-19 13:57 UTC, skriss commented
@sunjayBhatia good to merge here?

2021-05-19 14:19 UTC, merged