site: bulk replacement of Jekyll templates
projectcontour/contour pull request #3785
Opened 2021-06-08 16:43 UTC by skriss

Does the following replacements:

```
{{site.github.repository_url}}              {{< param github_url >}}
{{site.footer_social_links.Slack.url}}      {{< param slack_url >}}
{{page.version}}                            {{< param version >}}
{{site.latest}}                             {{< param latest_release_tag_name >}}
{{site.github.latest_release.tag_name}}     {{< param latest_release_tag_name >}}
```

Separately, going to file an issue to de-dupe `latest_release_tag_name` and `docs_latest` params, I think in practice they're always the same. I think we'll have to update our automation for this as well.

2021-06-08 16:44 UTC, skriss commented
Still need to test this with the site preview.

2021-06-08 17:01 UTC, skriss commented
Looks like `{{< param version >}}` doesn't work for the older site versions that aren't in https://github.com/projectcontour/contour/blob/main/site/config.yaml#L39-L52

2021-06-08 17:15 UTC, skriss commented
A quick spot-check looks good here

2021-06-08 17:47 UTC, stevesloka requested changes
All the `{{page.version}}` need to be replaced. Should be able to use `{{< param version >}}`

2021-06-08 17:49 UTC, stevesloka approved these changes
lgtm with the known issue with page_version.

2021-06-09 15:18 UTC, sunjayBhatia approved these changes

2021-06-09 19:16 UTC, merged