Update compatibility docs and release cutting notes
projectcontour/contour pull request #3796
Opened 2021-06-10 14:51 UTC by sunjayBhatia

- Adds release notes markdown template
- Calls out in release process doc about what to include in release
notes
- Modifies notes in compatibility matrix to remove ambiguity
- Minor updates in Philosophy document to bring it up to date

2021-06-10 15:08 UTC, skriss requested changes
I think this looks good, just a couple nits. I'd suggest also updating https://github.com/projectcontour/contour#prerequisites to have more general language along the lines of "refer to the compatibility matrix for supported versions" so we don't have to remember to update it.

2021-06-10 15:08 UTC, skriss commented on site/content/resources/philosophy.md
> +Contour currently supports Ingress v1, HTTPProxy and IngressRoute and we are working on supporting the Kubernetes Gateway API.
```suggestion
Contour currently supports Ingress v1 and HTTPProxy and we are working on supporting the Kubernetes Gateway API.
```

2021-06-10 15:08 UTC, skriss commented on site/content/resources/release-process.md
> +_Note: the PR will probably fail the siteproof check due to [#2032][3]. It's a good idea to scan the CI log for any true issues._
we can drop this line now since we no longer have the siteproof check

2021-06-10 15:08 UTC, skriss commented on site/content/resources/philosophy.md
> +Contour currently supports Ingress v1, HTTPProxy and IngressRoute and we are working on supporting the Kubernetes Gateway API.
no more IngressRoute :)

2021-06-10 15:14 UTC, sunjayBhatia commented on site/content/resources/philosophy.md
> +Contour currently supports Ingress v1, HTTPProxy and IngressRoute and we are working on supporting the Kubernetes Gateway API.
good catch!

2021-06-10 15:35 UTC, skriss approved these changes
LGTM

2021-06-10 19:14 UTC, stevesloka commented
Might need to also call out dropped support for Ingress v1beta1. I know it's removed from newer k8s versions, but could see users asking about this.

2021-06-11 18:16 UTC, skriss approved these changes

2021-06-15 16:15 UTC, merged