Add troubleshooting page
projectcontour/contour pull request #3830
Opened 2021-06-22 16:22 UTC by johnnycase

site/content/docs: Add troubleshooting page
Created a troubleshooting page and added a troubleshooting section to the main Docs page.

Updates #3816 
Signed-off-by: johnnycase <johneverettcase@gmail.com>

2021-06-23 16:19 UTC, stevesloka requested changes
Just one small nit, overall looks like a good start to build out the different sections. 

We might also want to include the FAQ (https://projectcontour.io/resources/faq/) page to link to or merge together someway.

2021-06-23 16:19 UTC, stevesloka commented on site/content/docs/main/troubleshooting.md
> +If you encounter issues, follow the guides below for help. For topics not covered here, you can [file an issue][0], or talk to us on the [#contour channel][1] on the Kubernetes Slack server.
```suggestion
If you encounter issues, follow the guides below for help. For topics not covered here, you can [file an issue][0], or talk to us on the [#contour channel][1] on Kubernetes Slack.
```

2021-06-23 19:59 UTC, johnnycase commented on site/content/docs/main/troubleshooting.md
> +If you encounter issues, follow the guides below for help. For topics not covered here, you can [file an issue][0], or talk to us on the [#contour channel][1] on the Kubernetes Slack server.
Looks good to me, thanks!

2021-06-24 01:14 UTC, youngnick approved these changes
This looks great, thanks.

2021-06-24 01:21 UTC, youngnick commented
Ah, it looks like your most recent commit needs the signoff @johnnycase. Personally, I use `git commit --amend -as` to fix this sort of thing up, that will update the last commit to have the signed-off-by line. You'll need to `git push --force` afterwards too. Or, if you did that with the online edit, unfortunately you need to fix this by pulling, editing locally, and repushing. Sorry, this is a Github limitation.

It's actually better to do stuff locally rather than use the UI for this reason, sadly.

Once the CI passes and the DCO is sorted, I'll merge this for you.

2021-06-24 17:11 UTC, johnnycase commented
i see, i'll make those edits and resubmit, thanks!

2021-06-25 06:01 UTC, youngnick commented
Dang, it looks like the second commit here is still not signed off. You could squash, or if you're not up for that, I can just squash as we merge.

2021-06-25 06:02 UTC, merged

2021-06-25 11:21 UTC, johnnycase commented
Thanks for merging! Sorry about the commit not being signed off. The command I used was git commit -s -m "Message" should I add anything there?