[Release 1.18] Cherry-pick: Allow retry policy, num retries to be zero
projectcontour/contour pull request #4174
Opened 2021-11-11 05:13 UTC by youngnick

Cherry-pick PR #4117 to release-1.18, in preparation for a 1.18.3 release.

Updates #4168

Original commit message below.
---
Since the current field for NumRetries is not a pointer, Contour
doesn't have a good way to understand if the field is unspecified,
or set to zero.

To keep the v1 API contract, Contour will allow this field to be set
to -1 which means the numRetries should be zero. If unspecified or set
to zero, then the Envoy default of 1 is used.

Signed-off-by: Steve Sloka <slokas@vmware.com>

2021-11-11 14:09 UTC, sunjayBhatia approved these changes

2021-11-11 15:01 UTC, skriss approved these changes

2021-11-11 16:02 UTC, stevesloka requested changes
Needs a code regen.

2021-11-12 00:13 UTC, youngnick commented
Merging this with admin powers so I can get the release cut.

2021-11-12 00:14 UTC, merged