Add support for "projectcontour.io/tls-cert-namespace" annotation
projectcontour/contour pull request #4271
Opened 2022-01-14 16:45 UTC by pablo-ruth

Hello,

Following the issue raised in #3544 we are maintaining an internal fork of Contour to be able to use TLS Delegation with Ingress v1. After a discussion with our Tanzu Solution Egineer @lzetea we decided that it could be interesting to propose our changes upstream.

We described our context [here](https://github.com/projectcontour/contour/issues/3544#issuecomment-831810882) to @xaleeks and it seems to be similar to @ghouscht [here](https://github.com/projectcontour/contour/issues/3544#issuecomment-833244403). 

@youngnick said that using an annotation could be the only way to go so I used this approach. I tried to keep the code simple and the change very small. It's backward compatible with "namespace/secret" syntax because the annotation is used only if namespace is blank. It doesn't cover the case where you have multiple TLS secrets from different namespaces.

2022-01-14 22:00 UTC, skriss reviewed
Thanks for the PR @pablo-ruth! I think this is a reasonable approach here for giving folks an option to keep using this functionality when moving to Ingress v1, but others with more of the backstory here can chime in as well.

Assuming we go forward with this, I'd also like to see some test cases added to:
- internal/dag/builder_test.go
- internal/featuretests/v3/tlscertificatedelegation_test.go

And some docs updates:
- https://projectcontour.io/docs/main/config/tls-delegation/
- https://projectcontour.io/docs/main/config/annotations/

2022-01-17 09:56 UTC, pablo-ruth commented on internal/annotation/annotations.go
> +		"projectcontour.io/tls-delegation-namespace":     {},
Yes it's better. I've done the renaming and tried to rename the functions to be coherent, what's your opinion on the new names ?

2022-01-18 23:50 UTC, skriss commented on internal/annotation/annotations.go
> +		"projectcontour.io/tls-delegation-namespace":     {},
👍  thanks for the updates, I think the naming looks great but others can weigh in as well. Will take a look at the other updates tomorrow, but we're hopeful we can get this into the upcoming 1.20 release!

2022-01-18 23:55 UTC, sunjayBhatia commented on internal/dag/builder_test.go
> +				SecretName: sec4.Namespace + "/" + sec4.Name,
```suggestion
				SecretName: sec4.Name,
```

2022-01-18 23:57 UTC, sunjayBhatia requested changes
i think one unit test to fix, included an Ingress with namespace in the secret name

2022-01-19 06:38 UTC, ghouscht commented
Looks like a good solution to me. However we went "all-in" with GatewayAPI together with contour in order to be able to update to k8s 1.22. Nevertheless I'd like to see this merged too 👍🏻

2022-01-19 13:35 UTC, pablo-ruth commented
Thanks @sunjayBhatia for the fix on the test, I merged it.

As discussed @skriss I added tests on both test files and updated the docs.

2022-01-19 15:53 UTC, skriss commented
@pablo-ruth thanks for those updates, they all LGTM. The last thing I see to do here is to add a changelog file, `changelogs/unreleased/4271-pablo-ruth-small.md`, with a one line description of the change (see https://github.com/projectcontour/contour/blob/main/changelogs/unreleased/small-sample.md). Or if you prefer to write a short paragraph that could include an example, use https://github.com/projectcontour/contour/blob/main/changelogs/unreleased/minor-sample.md and name your file `4271-pablo-ruth-minor.md`. Up to you.

2022-01-19 16:38 UTC, skriss approved these changes

2022-01-19 16:45 UTC, sunjayBhatia approved these changes

2022-01-19 17:27 UTC, merged

2022-01-19 17:27 UTC, skriss commented
Thanks again @pablo-ruth for contributing this change!

2022-01-19 17:33 UTC, pablo-ruth commented
Thanks for your guidance !