HTTPProxy: add healthCheck port config
projectcontour/contour pull request #4761
Opened 2022-09-29 07:41 UTC by yangyy93

Add healthCheck port for httproute and tcproute

fix https://github.com/projectcontour/contour/issues/4655
Signed-off-by: yy [yang.yang@daocloud.io]

2022-10-04 02:50 UTC, sunjayBhatia commented on apis/projectcontour/v1/httpproxy.go
> +	// +kubebuilder:validation:Maximum=65536
should add the `+optional` annotation here as well

2022-10-04 02:51 UTC, sunjayBhatia commented on apis/projectcontour/v1/httpproxy.go
> +	// if the field were not specified, it is the same as Port.
```suggestion
	// If not specified, Port is used for service healthchecks.
```

2022-10-04 02:52 UTC, sunjayBhatia commented on changelogs/unreleased/4761-yangyy93-minor.md
> +HTTPProxy.Route.Service and HTTPProxy.TCPProxy.Service now has a `HealthPort` which specifies a health check port that is different from the routing port.If the field was not specified,it is the same
```suggestion
HTTPProxy.Route.Service and HTTPProxy.TCPProxy.Service now has a `HealthPort` field which specifies a health check port that is different from the routing port. If not specified, the service `Port` field is used for healthchecking.
```

2022-10-05 15:08 UTC, skriss requested changes
Thanks for the PR @yangyy93!

Please also add some documentation to https://github.com/projectcontour/contour/blob/main/site/content/docs/main/config/health-checks.md on this new feature.

2022-10-18 06:04 UTC, yangyy93 commented on apis/projectcontour/v1/httpproxy.go
> +	// if the field were not specified, it is the same as Port.
thanks for your comment

2022-10-18 06:08 UTC, yangyy93 commented on apis/projectcontour/v1/httpproxy.go
> +	// +kubebuilder:validation:Maximum=65536
thanks for your comment，the relevant documents have been supplemented

2022-10-18 06:21 UTC, yangyy93 commented
Thank you for your comments, the relevant documents and comments have been revised.
@skriss @sunjayBhatia

2022-10-18 18:19 UTC, skriss requested changes
Thanks for the updates @yangyy93, two more small comments.

2022-10-19 02:33 UTC, yangyy93 commented on internal/dag/accessors.go
> +	}
Thanks for your comments

2022-10-19 14:01 UTC, skriss approved these changes
LGTM, will leave for @sunjayBhatia to take another look

2022-10-19 14:26 UTC, sunjayBhatia commented on internal/envoy/v3/endpoint_test.go
> +				HealthCheckConfig: HealthCheckConfig(8998),
would prefer this not use a helper to fill in this field but rather explicitly write out the object we expect, just to ensure we're not using something under test to generate the expected value

2022-10-19 14:40 UTC, sunjayBhatia commented on internal/dag/accessors_test.go
> +					Name:       "heath",
nit
```suggestion
					Name:       "health",
```

2022-10-19 14:41 UTC, sunjayBhatia requested changes
logic looks good, but some changes requested on the structure of the endpointstranslator tests

2022-10-25 06:30 UTC, yangyy93 commented
> 逻辑看起来不错，但需要对端点翻译器测试的结构进行一些更改

do you have any other suggestions？

2022-10-25 06:32 UTC, yangyy93 commented
> logic looks good, but some changes requested on the structure of the endpointstranslator tests

do you have any other suggestions？ @sunjayBhatia

2022-10-28 14:33 UTC, skriss commented
@sunjayBhatia I think this one's just awaiting another look from you

2022-10-28 15:49 UTC, sunjayBhatia approved these changes
lgtm, I may make a follow up PR since that is a little easier to fix some test things

2022-10-28 16:18 UTC, merged

2022-10-28 16:30 UTC, sunjayBhatia commented
follow up: https://github.com/projectcontour/contour/pull/4828