XFCC header support
projectcontour/contour pull request #4797
Opened 2022-10-17 13:21 UTC by gautierdelorme

This is required to let apps use details from client certificates (e.g. Subject, SAN...). Since the certificate (or the certificate chain) could exceed the web server header size limit, we give the ability to select what specific part of the certificate to expose in the `x-forwarded-client-cert` header.

Fixes https://github.com/projectcontour/contour/issues/2885 (I've read through this issue and since that feature is only usable when `ClientValidation` is used (since that's required for the server to request certs) I think having `ForwardClientCertificate` under `ClientValidation` makes more sense)

Signed-off-by: Gautier Delorme <gautier.delorme@gmail.com>

2022-10-19 15:03 UTC, gautierdelorme commented
Do you think this change could make it to the 1.23 release?

2022-10-19 23:39 UTC, skriss commented
> Do you think this change could make it to the 1.23 release?

Unfortunately it's too late to get these into 1.23, but we'll pick up with reviews shortly.

2022-10-20 15:35 UTC, tsaarni requested changes
Looking very good :+1: Just one tiny remark from me.

2022-10-20 19:38 UTC, gautierdelorme commented on internal/dag/dag.go
> +	// +optional
Totally 👍 Fixed in https://github.com/projectcontour/contour/pull/4797/commits/b7e8dabc5939ecb37b162751baf3521421cc0417.

2022-10-21 04:03 UTC, tsaarni requested changes
Needs merging & regenerating after the other PR was merged, but otherwise ready to go from my perspective.

2022-10-21 07:58 UTC, tsaarni approved these changes
Thank you @gautierdelorme :+1: 
Leaving for others to review as well.

2022-10-21 14:39 UTC, skriss approved these changes
LGTM, thanks @gautierdelorme! Will leave open for a bit in case @sunjayBhatia wants to take a look.

2022-10-21 15:10 UTC, sunjayBhatia approved these changes
looks great!

one thing that could be useful to help troubleshoot header size issues would be to enable upstream cluster req/resp statistics: https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats#request-response-size-statistics

I can add a new issue for that so we can consider it (if we dont have one already)

2022-10-21 15:22 UTC, merged