Add grpc_status_code as a default access log field
projectcontour/contour pull request #4880
Opened 2022-11-30 11:45 UTC by rajatvig

Fixes https://github.com/projectcontour/contour/issues/4484

Signed-off-by: Rajat Vig <rvig@etsy.com>

2022-12-08 09:41 UTC, rajatvig commented
Could this be reviewed please?

2022-12-15 21:18 UTC, skriss requested changes
One minor comment on the changelog, otherwise LGTM.

cc @sunjayBhatia

2022-12-15 21:18 UTC, skriss commented on changelogs/unreleased/4880-rajatvig-small.md
> +Add `grpc_status_code` to the log message field
```suggestion
Add `grpc_status_number` to the default JSON access log fields
```

2022-12-15 22:18 UTC, sunjayBhatia commented on apis/projectcontour/v1alpha1/accesslog.go
> +	"grpc_status_number",
huh seems like we already added this to `envoySimpleOperators` in this file

2022-12-15 22:19 UTC, sunjayBhatia commented on apis/projectcontour/v1alpha1/accesslog.go
> +	"grpc_status_number",
(the access log format operator version)

2022-12-15 22:20 UTC, sunjayBhatia approved these changes
might want to be more judicious about the default access log fields in the future, but seems good to add this one

2022-12-15 22:21 UTC, sunjayBhatia commented
> might want to be more judicious about the default access log fields in the future, but seems good to add this one

lgtm minus @skriss' comments I should say

2022-12-15 22:53 UTC, rajatvig commented
> > might want to be more judicious about the default access log fields in the future, but seems good to add this one
> 
> lgtm minus @skriss' comments I should say

Addressed the comments. Agree, the default access log fields should only be judiciously added.

2022-12-16 14:24 UTC, skriss approved these changes

2022-12-16 14:25 UTC, skriss commented
Thanks @rajatvig!

2022-12-16 14:25 UTC, merged