enable TLSRoute service reference in serviceTriggersRebuild
projectcontour/contour pull request #4915
Opened 2022-12-09 05:07 UTC by vmw-yingy

enable DAG rebuild for service referenced by TLSRoutes

Signed-off-by: Yu Ying <yingy@vmware.com>

2022-12-09 05:08 UTC, vmw-yingy commented
@skriss @sunjayBhatia Please help review

2022-12-13 14:12 UTC, sunjayBhatia approved these changes

2022-12-13 14:15 UTC, sunjayBhatia commented
One last thing before we merge this @vmw-yingy, it would be create if you could add a changelog file following the guidelines here: https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines, in this case a `small` changelog

2022-12-13 23:17 UTC, sunjayBhatia commented on changelogs/unreleased/4915-yingy-small.md
> +enable TLSRoute service reference in serviceTriggersRebuild
suggestion on the wording, to make it more user focused
```suggestion
Ensure changes to Services referenced by TLSRoutes trigger xDS configuration updates.
```

2022-12-14 18:04 UTC, sunjayBhatia commented on changelogs/unreleased/4915-yingy-small.md
> +Ensure changes to Services referenced by TLSRoute trigger xDS configuration updates.
oh oops, didnt catch it but the filename should be `4915-vmw-yingy-small.md` to get your full github username in

2022-12-14 18:04 UTC, sunjayBhatia requested changes
changelog filename needs an update

2022-12-14 18:49 UTC, skriss reviewed
LGTM once the changelog filename is updated.

I'm thinking we can hold off on merging until we merge the `dev-gwapi-0.6` branch into `main` (which should be soon, the GWAPI 0.6.0 release should be out this week or next). Would keep the commit history a little cleaner.

2022-12-14 21:10 UTC, sunjayBhatia approved these changes

2022-12-14 21:16 UTC, skriss approved these changes

2022-12-14 22:33 UTC, skriss commented
Now that we've merged the `dev-gwapi-0.6` branch into `main`, we'll want to rebase this PR onto `main` and target `main` to get it merged. We can walk through this together on Friday.

2022-12-15 15:28 UTC, skriss commented
I re-targeted the PR to main; the branch now needs to be rebased on upstream/main.

2022-12-15 23:05 UTC, merged