expose configuration for envoy's RateLimitedAsResourceExhausted
projectcontour/contour pull request #4971
Opened 2023-01-10 18:30 UTC by vroldanbet

Closes https://github.com/projectcontour/contour/issues/4901

The Rate Limit filter in Envoy translates a 429 HTTP response code to UNAVAILABLE as specified in the gRPC mapping document, but Google recommends translating it to RESOURCE_EXHAUSTED
(see https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md)

This commit introduces a new setting to allow contour to forward the same parameter introduced in https://github.com/envoyproxy/envoy/pull/4879

The default value is disabled to retain the original behaviour of returning UNAVAILABLE, as changing it would be a breaking change.

This PR is largely inspired in the work done at https://github.com/projectcontour/contour/pull/3457

FYI @sunjayBhatia as we discussed about this in https://github.com/projectcontour/contour/issues/4901

2023-01-11 19:34 UTC, skriss commented
Thanks for the PR @vroldanbet! Please run `make generate` and commit the results to get the codegen CI check to pass.

2023-01-11 19:40 UTC, skriss commented
Please also address https://github.com/projectcontour/contour/actions/runs/3895937483/jobs/6651861120, the output has instructions to follow. Thanks!

2023-01-11 20:16 UTC, vroldanbet commented
@skriss done! Ready for another CI run!

2023-01-11 22:36 UTC, skriss requested changes

2023-01-11 22:36 UTC, skriss commented on examples/contour/01-crds.yaml
> +description: ResourceClaim references one entry in PodSpec.ResourceClaims.
We just merged https://github.com/projectcontour/contour/pull/4972 to fix this whitespace problem for macOS, if you could rebase your branch on `main` and re-run `make generate` it should go away.

2023-01-12 15:53 UTC, skriss commented
Looks like one UT still needs to be updated for the new field (https://github.com/projectcontour/contour/blob/main/cmd/contour/servecontext_test.go#L623-L645), otherwise this looks good to me

2023-01-12 19:33 UTC, vroldanbet commented
@skriss just pushed the fix, thanks for your patience and prompt feedback 🙏🏻

2023-01-12 19:58 UTC, sunjayBhatia approved these changes

2023-01-12 20:33 UTC, skriss approved these changes
LGTM, thanks @vroldanbet!

2023-01-12 20:34 UTC, merged