internal/provisioner: add support to NodePortServicePublishingType
projectcontour/contour pull request #4973
Opened 2023-01-12 07:08 UTC by izturn

Signed-off-by: Gang Liu <gang.liu@daocloud.io>

Add support to `NodePortServicePublishingType`

fix #4499

2023-01-12 16:12 UTC, skriss requested changes

2023-01-12 16:12 UTC, skriss commented on changelogs/unreleased/4973-izturn-small.md
> +Add support to `NodePortServicePublishingType`. fix [#4499](https://github.com/projectcontour/contour/issues/4499).
```suggestion
Gateway API: when provisioning an Envoy `NodePortService`, use the Listeners' port numbers to populate the Service's node port values.
```

2023-01-13 06:03 UTC, skriss approved these changes
LGTM, thanks @izturn!

2023-01-13 07:27 UTC, izturn commented
> Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
> 
> Add support to `NodePortServicePublishingType`
> 
> fix #4499 fix #4724

@skriss maybe we need to do some adjust to `ContourDeployment` for `LoadBalancer`, so it would better to keep the #4724 open.

2023-01-13 17:14 UTC, skriss commented
> > Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
> > Add support to `NodePortServicePublishingType`
> > fix #4499 fix #4724
> 
> @skriss maybe we need to do some adjust to `ContourDeployment` for `LoadBalancer`, so it would better to keep the #4724 open.

That issue was helpful for organizing the initial wave of PRs but now that everything on there has merged, I think we can close it out. Please open new issues for additional features!

2023-01-13 17:48 UTC, sunjayBhatia commented on apis/projectcontour/v1alpha1/contourdeployment.go
> +	// When provisioning an Envoy `NodePortService`, use the Listeners' port numbers to populate
nit: to make it clear we're talking about the Gateway Listener configuration not an Envoy Listener
```suggestion
	// When provisioning an Envoy `NodePortService`, use Gateway Listener port numbers to populate
```

2023-01-13 17:50 UTC, sunjayBhatia reviewed
tried this out manually yesterday and it looks good, just one nit comment on some wording

2023-01-14 16:31 UTC, izturn commented
> > > Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
> > > Add support to `NodePortServicePublishingType`
> > > fix #4499 fix #4724
> > 
> > 
> > @skriss maybe we need to do some adjust to `ContourDeployment` for `LoadBalancer`, so it would better to keep the #4724 open.
> 
> That issue was helpful for organizing the initial wave of PRs but now that everything on there has merged, I think we can close it out. Please open new issues for additional features!

got it

2023-01-17 15:32 UTC, skriss approved these changes
LGTM, leaving for @sunjayBhatia

2023-01-17 16:00 UTC, sunjayBhatia approved these changes

2023-01-17 17:15 UTC, merged