feat: Add AllowPrivateNetwork to support Access-Control-Allow-Private…
projectcontour/contour pull request #5034
Opened 2023-01-31 14:21 UTC by lvyanru8200

…-Network

Fixes: https://github.com/projectcontour/contour/issues/4553
Signed-off-by: tigerK <yanru.lv@daocloud.io>

2023-01-31 14:28 UTC, lvyanru8200 commented
cc @skriss @stevesloka

2023-02-01 20:17 UTC, skriss commented
Thanks for the PR @lvyanru8200! Please add a changelog file per the instructions in https://github.com/projectcontour/contour/actions/runs/4068330638/jobs/7006764495. You'll also need to run `make generate` and commit the changed files.

2023-02-01 20:20 UTC, skriss commented on internal/featuretests/v3/corspolicy_test.go
> +	//
Fill in comment here 😁

2023-02-02 02:54 UTC, lvyanru8200 commented
cc @skriss

2023-02-02 22:46 UTC, skriss commented
Looks like a few more failing unit tests to update.

2023-02-03 03:05 UTC, lvyanru8200 commented
cc @skriss

2023-02-03 16:00 UTC, skriss requested changes
Code LGTM. The last thing is to update the docs (https://github.com/projectcontour/contour/blame/main/site/content/docs/main/config/cors.md)

I think mentioning this in https://github.com/projectcontour/contour/blame/main/site/content/docs/main/config/cors.md#L7, plus adding it to one of the YAML examples with a sentence or comment explaining it, should be sufficient.

2023-02-07 03:51 UTC, lvyanru8200 commented
cc @skriss

2023-02-07 15:37 UTC, skriss approved these changes
LGTM, thanks @lvyanru8200.

2023-02-07 17:19 UTC, merged