internal/provisioner: expose the metrics port for envoy
projectcontour/contour pull request #5101
Opened 2023-02-17 08:05 UTC by izturn

Expose the default/changed metric port for envoy

Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

2023-03-29 01:40 UTC, izturn commented
ping @sunjayBhatia @skriss

2023-03-29 14:38 UTC, Jean-Daniel commented
Is the usage of --stats-port flag required ?
The last time I tried, I saw that contour was directly using the value from its `contourConfiguration` to configure the envoy metric listener. 

So I don't think there is a need to add an extra flag to the contour deployment.

2023-04-04 20:11 UTC, skriss commented on internal/provisioner/controller/gateway.go
> +				})
This has the effect of exposing the metrics port on the Service, which we don't do when using the default port and I don't think we want to do for custom ports. Were you intentionally trying to expose it on the Service? If so, could explain the thinking further

2023-04-10 01:43 UTC, izturn commented
ok, i will upgrade it

2023-05-06 02:24 UTC, izturn commented
gentle ping  @skriss @sunjayBhatia

2023-05-08 21:45 UTC, skriss requested changes
Couple nits, but otherwise looks reasonable 👍

2023-05-08 21:45 UTC, skriss commented on internal/provisioner/objects/deployment/deployment.go
> +
Let's revert the no-op changes to deployment.go and deployment_test.go, for clarity in the commit.

2023-05-08 21:45 UTC, skriss commented on internal/provisioner/objects/deployment/deployment_test.go
> +	// Use non-default container ports to test that
Let's revert the no-op changes to deployment.go and deployment_test.go, for clarity in the commit.

2023-05-08 21:46 UTC, skriss commented
Please add a changelog file as well.

2023-05-18 14:36 UTC, skriss requested changes

2023-05-18 14:36 UTC, skriss commented on changelogs/unreleased/5101-izturn-small.md
> +Expose the default/changed metric port for envoy
```suggestion
Gateway provisioner: add a container port to the Envoy daemonset/deployment for the metrics port.
```

2023-05-18 14:36 UTC, skriss commented on internal/provisioner/objects/dataplane/dataplane.go
> +		healthPort  = 8002
while we're here, it'd be nice to move this constant into `object.go` along with the other port numbers, similar to `EnvoyMetricsPort`.

2023-05-22 14:50 UTC, skriss approved these changes
LGTM, thanks @izturn

2023-05-22 15:35 UTC, merged