Do not use hard-coded values, but configuration defined ports.
projectcontour/contour pull request #5233
Opened 2023-03-29 13:45 UTC by Jean-Daniel

This fix an issue with envoy pods generated by contour provisioner.

Envoy pods are never declared `Ready` when using a custom health port.
Envoy exposes the wrong port in prometheus annotations when using a custom metrics port.

2023-04-04 20:18 UTC, skriss requested changes

2023-04-04 20:18 UTC, skriss commented on internal/provisioner/objects/dataplane/dataplane.go
> +						Port:   intstr.IntOrString{IntVal: int32(contour.Spec.RuntimeSettings.Envoy.Health.Port)},
This reference is nil by default which is resulting in a panic. We'll need to add some nil-checking and defaulting here. Please also add unit tests that cover this for the default and non-default cases.

2023-04-05 18:40 UTC, skriss commented
Thanks for the update @Jean-Daniel -- last two things are to [add a changelog file](https://github.com/projectcontour/contour/actions/runs/4621735162/jobs/8173532461?pr=5233) and [add DCO signoff to your commits](https://github.com/projectcontour/contour/pull/5233/checks?check_run_id=12532013872).

2023-04-06 18:19 UTC, skriss approved these changes

2023-04-06 19:54 UTC, sunjayBhatia approved these changes

2023-04-06 19:55 UTC, merged