Gateway API: support regex path and header match
projectcontour/contour pull request #5239
Opened 2023-03-31 22:59 UTC by fangfpeng

- support regex path and regex header match for HTTPRoute.
- support regex header match for GRPCRoute.

Fixes #3357
Fixes #5219

2023-04-07 19:59 UTC, skriss requested changes
Thanks for this @fangfpeng! Couple comments

2023-04-07 19:59 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +				return nil, fmt.Errorf("HTTPRoute.Spec.Rules.Matches.Headers: Only Exact type and RegularExpressionmatch type are supported")
nit:
```suggestion
				return nil, fmt.Errorf("HTTPRoute.Spec.Rules.Matches.Headers: Only Exact type and RegularExpression match type are supported")
```

2023-04-07 19:59 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +			MatchType: matchType,
For regex, we should validate that it's a valid regex and return an error if not. We have a `ValidateRegex` function in this package that you can use.

2023-04-07 19:59 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +			return &RegexMatchCondition{Regex: path}, true
Same comment re: validating the regex

2023-04-07 19:59 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +	if *match.Type == gatewayapi_v1beta1.PathMatchExact || *match.Type == gatewayapi_v1beta1.PathMatchRegularExpression {
I don't think we need to add regex matches here -- these checks only apply for exact or prefix matches:

> PathPrefix and Exact paths must be syntactically valid:
> 
> - Must begin with the / character
> - Must not contain consecutive / characters (e.g. /foo///, //).

(ref. https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.PathMatchType)

2023-04-07 19:59 UTC, skriss commented on internal/dag/gatewayapi_processor.go
>  			Value:     match.Value,
same comment re: validating the regex

2023-04-07 22:24 UTC, skriss requested changes

2023-04-07 22:24 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +			switch *match.Type {
Could simplify this a bit using a generic helper we have for defaulting a nil pointer:
```suggestion
		switch ref.Val(match.Type, gatewayapi_v1beta1.HeaderMatchExact) {
```

2023-04-07 22:24 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +			switch *match.Type {
Same simplification here:
```suggestion
		switch ref.Val(match.Type, gatewayapi_v1beta1.HeaderMatchExact) {
```

2023-04-10 18:53 UTC, skriss approved these changes
Thanks for the updates @fangfpeng, LGTM!

2023-04-11 14:52 UTC, sunjayBhatia commented on internal/dag/builder_test.go
> +func regrexrouteHTTPRoute(path string, first *Service, rest ...*Service) *Route {
tiny typo nit
```suggestion
func regexrouteHTTPRoute(path string, first *Service, rest ...*Service) *Route {
```

2023-04-11 18:46 UTC, merged