fix some comments
projectcontour/contour pull request #5316
Opened 2023-04-25 06:58 UTC by cuishuang

2023-04-27 15:25 UTC, skriss requested changes
@cuishuang it looks like there are still many typos/grammatical issues in your updates, can you take another pass through this? Thanks.

2023-04-27 15:25 UTC, skriss commented on apis/projectcontour/v1/httpproxy.go
> +	// strategy will fall back thedefault `RoundRobin`.
```suggestion
	// strategy will fall back to the default `RoundRobin`.
```

2023-04-27 15:54 UTC, sunjayBhatia requested changes

2023-04-27 15:54 UTC, sunjayBhatia commented on apis/projectcontour/v1/httpproxy.go
> +	// strategy will fall back the  default `RoundRobin`.
```suggestion
	// strategy will fall back to the default `RoundRobin`.
```

2023-04-27 15:54 UTC, sunjayBhatia commented on cmd/contour/ingressstatus.go
> +// the ory of operation of the loadBalancerStatusWriter is as follows:
This should not be changed

2023-04-27 15:54 UTC, sunjayBhatia commented on internal/provisioner/model/model.go
> +	// If unspecified, a port number will be assigned from the  cluster's
```suggestion
	// If unspecified, a port number will be assigned from the cluster's
```

here and other places there should not be an extra space

2023-04-27 15:57 UTC, sunjayBhatia commented on apis/projectcontour/v1/httpproxy.go
> +	// strategy will fall back the default `RoundRobin`.
again, `to the` here.

2023-04-27 17:12 UTC, skriss commented on examples/contour/01-crds.yaml
> +                        the secret will be delegated to. If TargetNamespaces is
You will need to make this change in the `tlscertificatedelegation.go` file in `apis/projectcontour/v1`, and then run `make generate to ensure all of the generated YAML is in sync with it.

2023-04-28 13:26 UTC, skriss commented on examples/contour/01-crds.yaml
> +                        the secret will be delegated to. If TargetNamespaces is
Still need to run `make generate` and commit the results..

2023-04-28 18:22 UTC, skriss commented on examples/contour/01-crds.yaml
> +                        the secret will be delegated to. If TargetNamespaces is
Hmm, not sure what error you're getting. Is it OK if I push the update to your branch?

2023-04-29 13:48 UTC, skriss commented on examples/contour/01-crds.yaml
> +                        the secret will be delegated to. If TargetNamespaces is
Done

2023-04-29 14:26 UTC, skriss approved these changes
LGTM, thanks @cuishuang

2023-05-01 13:39 UTC, merged