rename interface{} to any
projectcontour/contour pull request #5423
Opened 2023-05-30 07:11 UTC by izturn

Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

2023-05-31 18:09 UTC, skriss requested changes

2023-05-31 18:09 UTC, skriss commented on design/custom-request-timeout.md
> +    object          any
We can omit the design docs from this update, no need to touch them.

2023-05-31 18:09 UTC, skriss commented on design/loadbalancer-hash-policy-design.md
> +### Using `map[string]any` for `HashOptions` Type
can omit changes to this file

2023-06-01 14:15 UTC, skriss requested changes

2023-06-01 14:15 UTC, skriss commented on design/loadbalancer-hash-policy-design.md
> +We would likely have to implement a type alias to `any` and write some custom deep copy code to support this rather than rely on types that work with out of the box tooling.
please revert this change too

2023-06-01 14:15 UTC, skriss commented on design/loadbalancer-hash-policy-design.md
> +This option was considered and not chosen because using `any` as the value type of the options map out of the box does not work with the deep copy infrastructure we have.
please revert this change too

2023-06-02 02:23 UTC, izturn commented on design/loadbalancer-hash-policy-design.md
> +We would likely have to implement a type alias to `any` and write some custom deep copy code to support this rather than rely on types that work with out of the box tooling.
done

2023-06-02 14:58 UTC, skriss approved these changes

2023-06-02 15:00 UTC, skriss commented
@izturn I think if we want this to be a standard, then we need to add a linter for this, otherwise folks are likely to add back usage of `interface{}` in the future. Can you add that to this PR?

2023-06-03 00:31 UTC, izturn commented
ok, i will add a linter for it

2023-06-03 03:21 UTC, izturn commented
@skriss  PTAL

2023-06-05 17:50 UTC, skriss approved these changes

2023-06-05 18:33 UTC, merged