add more information in Error Message of httpproxy
projectcontour/contour pull request #5670
Opened 2023-08-10 02:58 UTC by HeavenTonight

fixed #5638 
add more information in Error Message of httpproxy

2023-08-17 19:12 UTC, skriss commented
There are also some failing unit tests that need to be looked into.

2023-08-17 19:17 UTC, sunjayBhatia commented on internal/dag/httpproxy_processor.go
> +				"root httpproxy cannot include another root httpproxy,child httpproxy info is [namespace:%s name:%s]", includedProxy.Namespace, includedProxy.Name)
yep that works for me 👍🏽 concise and effective

2023-08-23 14:52 UTC, skriss requested changes
There are still some failing tests to fix per below comments. Also, please add a changelog file by following the instructions at https://github.com/projectcontour/contour/actions/runs/5949094558/job/16145697974?pr=5670

2023-08-23 14:52 UTC, skriss commented on internal/dag/status_test.go
> +				WithError(contour_api_v1.ConditionTypeIncludeError, "RootIncludesRoot", fmt.Sprintf("root httpproxy cannot include another root httpproxy (%s/%s)", proxyIncludesRootDifferentFQDN.Namespace, proxy
The namespace/name here should be of the child proxy, not the parent:
```suggestion
				WithError(contour_api_v1.ConditionTypeIncludeError, "RootIncludesRoot", fmt.Sprintf("root httpproxy cannot include another root httpproxy (%s/%s)", proxyRootIncludedByRootDiffFQDN.Namespace, proxyRootIncludedByRootDiffFQDN.Name)),
```

2023-08-23 14:52 UTC, skriss commented on internal/dag/status_test.go
> +				WithError(contour_api_v1.ConditionTypeTCPProxyIncludeError, "RootIncludesRoot", fmt.Sprintf("root httpproxy cannot include another root httpproxy (%s/%s)", proxyTCPIncludesFoo.Namespace, proxyTCP
The namespace/name here should be of the child proxy, not the parent:
```suggestion
				WithError(contour_api_v1.ConditionTypeTCPProxyIncludeError, "RootIncludesRoot", fmt.Sprintf("root httpproxy cannot include another root httpproxy (%s/%s)", proxyValidTCPRoot.Namespace, proxyValidTCPRoot.Name)),
```

2023-08-24 01:34 UTC, HeavenTonight commented
> There are still some failing tests to fix per below comments. Also, please add a changelog file by following the instructions at https://github.com/projectcontour/contour/actions/runs/5949094558/job/16145697974?pr=5670
> 
> 根据以下评论，仍有一些失败的测试需要修复。 另外，请按照 https://github.com/projectcontour/contour/actions/runs/5949094558/job/16145697974?pr=5670 中的说明添加更改日志文件

thinks for review,i will fix it soon !

2023-08-24 13:08 UTC, sunjayBhatia requested changes

2023-08-24 13:08 UTC, sunjayBhatia commented on changelogs/unreleased/5670-HeavenTonight-small.md
> +Add namespace or child proxy name in the message when Root httpproxy will be invalid if child proxies are not config correctly.
```suggestion
Add included HTTPProxy namespace and name to status condition error message when a root HTTPProxy includes another root.
```

2023-08-25 01:25 UTC, HeavenTonight commented on changelogs/unreleased/5670-HeavenTonight-small.md
> +Add namespace or child proxy name in the message when Root httpproxy will be invalid if child proxies are not config correctly.
Thanks for review 😉

2023-08-25 18:55 UTC, skriss approved these changes
LGTM, thanks @HeavenTonight

2023-08-25 20:20 UTC, merged