provisioner: add field overloadMaxHeapSize for envoy
projectcontour/contour pull request #5699
Opened 2023-08-22 07:05 UTC by yangyy93

close #5662

2023-09-06 05:52 UTC, tsaarni commented on changelogs/unreleased/5699-yangyy93-small.md
> +Gateway configuration program: Add the `overloadMaxHeapSize` configuration option to contourDeployment to allow adding [overloadManager](https://projectcontour.io/docs/main/config/overload-manager/)
Just a minor nit: could you change Gateway configuration program to Gateway provisioner as that has been used in the past as a prefix for changelog entries.

2023-09-06 06:03 UTC, tsaarni requested changes
Thank you @yangyy93, looks good to me! 

The description of the parameter that you have added in your PR is so much better than my original description of the bootstrap flag here
https://github.com/projectcontour/contour/blob/f3f1484a99e75f62a946956df2dfb84109fa72ef/site/content/docs/main/configuration.md?plain=1#L513

If I may ask, would you mind changing `site/content/docs/main/configuration.md` and aligning it by using your description instead:

```
| <nobr>--overload-max-heap              | 0                | Defines the maximum heap memory of the envoy controlled by the overload manager. When the value is greater than 0, the overload manager is enabled, and when envoy reaches 95% of the maximum heap size, it performs a shrink heap operation. When it reaches 98% of the maximum heap size, Envoy Will stop accepting requests. |
```

2023-09-06 08:53 UTC, yangyy93 commented
> Thank you @yangyy93, looks good to me!
> 
> The description of the parameter that you have added in your PR is so much better than my original description of the bootstrap flag here
> 
> https://github.com/projectcontour/contour/blob/f3f1484a99e75f62a946956df2dfb84109fa72ef/site/content/docs/main/configuration.md?plain=1#L513
> 
> If I may ask, would you mind changing `site/content/docs/main/configuration.md` and aligning it by using your description instead:
> 
> ```
> | <nobr>--overload-max-heap              | 0                | Defines the maximum heap memory of the envoy controlled by the overload manager. When the value is greater than 0, the overload manager is enabled, and when envoy reaches 95% of the maximum heap size, it performs a shrink heap operation. When it reaches 98% of the maximum heap size, Envoy Will stop accepting requests. |
> ```

thanks, I have updated the relevant documentation.

2023-09-06 09:54 UTC, tsaarni approved these changes

2023-09-21 04:44 UTC, tsaarni approved these changes
Thank you @yangyy93!

2023-09-21 04:44 UTC, merged