httpproxy: adjust the order for filter: AuthZ & AuthN
projectcontour/contour pull request #5840
Opened 2023-10-12 10:42 UTC by izturn

put the filter: Authz after AuthN

Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

2023-10-12 10:48 UTC, tsaarni commented
Hi @izturn! :wave:  You could add `closes #4826` to the description.

2023-10-13 02:05 UTC, izturn commented
@tsaarni sorry, i don't see it, i find it when do ext_proc, ;-)

2023-10-13 09:23 UTC, tsaarni commented
@izturn please add changelog entry. This is change to external behavior and it is good to notify users in release notes.

I'm in favor of this PR as discussed previously in #4826.

2023-11-02 03:37 UTC, izturn commented
@tsaarni PTAL

2023-11-07 22:23 UTC, skriss requested changes

2023-11-07 22:23 UTC, skriss commented on changelogs/unreleased/5840-izturn-small.md
> +Rearrange the order of filters, put the external authorization filter after the JWT verification filter.
Let's bump this up to minor, and re-word a bit for clarity for users:

```suggestion
## JWT Authentication happens before External Authorization

Fixes a bug where when the external authorization filter and JWT authentication filter were both configured, the external authorization filter was executed _before_ the JWT authentication filter.  Now, JWT authentication happens before external authorization when they are both configured.
```

2023-11-07 22:23 UTC, skriss commented on internal/xdscache/v3/listener.go
> +					AddFilter(envoy_v3.FilterJWTAuthN(vh.JWTProviders)).
Ideally we can add a test case for this. I won't block the PR on it, but it would be very nice to have.

2023-11-14 01:42 UTC, izturn commented
@sunjayBhatia  @skriss  PTAL

2023-11-14 22:34 UTC, skriss approved these changes
LGTM, will leave for another maintainer to take a second look as well, thanks @izturn

2023-11-15 15:27 UTC, tsaarni approved these changes

2023-11-15 16:12 UTC, merged