enabled trackRemaining in Envoy
projectcontour/contour pull request #5945
Opened 2023-11-08 18:15 UTC by satyazzz123

Enabled TrackRemaining in Envoy via Contour proxy or annotations.

updates : #5794

2023-11-08 18:18 UTC, satyazzz123 commented
@sunjayBhatia Please review the code changes. Thank you!

2023-11-09 16:36 UTC, sunjayBhatia commented on internal/envoy/v3/cluster.go
> +				TrackRemaining:     protobuf.BoolOrNil(true),
the type of this field is just `bool`

2023-11-09 16:37 UTC, sunjayBhatia requested changes
please also provide a `small` release note, following the guidelines here: https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

2023-11-11 15:30 UTC, satyazzz123 commented
@sunjayBhatia i have opened another PR #5950 and closing this one as this branch was posing some issue in my local system. Sorry for the inconvenience.

2023-11-11 15:30 UTC, closed without merging