Gateway API: fix for failing GatewayWithAttachedRoutes conformance test
projectcontour/contour pull request #5961
Opened 2023-11-14 09:59 UTC by izturn

Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)

fix #5922

2023-11-14 19:42 UTC, sunjayBhatia reviewed
just a requested change on the release note so far but from a quick look at the test changes/code changes this looks like it achieves what looks like the right outcome for the most part, though ends up being a little repetitive

With this change, we're processing Listeners/Routes multiple times now, once looping through the Listeners for finding which ones are valid, then going through each Listener/Route another time for seeing if the Routes can attach/intersect hostnames, then doing the Listener/Route analysis *again* for the purposes of calculating attached route counts. It would be good to coalesce some of this logic together since it seems like extra processing we could reduce.

Maybe this looks like not returning early from `computeListener` and including the error of why the listener is invalid/if it should still be allowed to have attached routes in the returned `listenerInfo` struct

This isn't something the upstream conformance tests are checking yet, but if this doesn't exist would be good to ensure a test exists for a Gateway Listener that has an invalid configuration in its route selection (e.g. invalid namespace selector due to a field missing or invalid route kind) but a Route with a parent ref that would be valid should still not count

2023-11-14 19:42 UTC, sunjayBhatia commented on internal/dag/status.go
> +
nit: can remove this diff

2023-11-27 02:39 UTC, izturn commented
ping @sunjayBhatia

2023-12-05 23:18 UTC, sunjayBhatia commented on internal/dag/status_test.go
> +	run(t, "HTTP listener, route's parent ref route kind is invalid", testcase{
nit
```suggestion
	run(t, "HTTP listener with invalid AllowedRoute kind referenced by route parent ref", testcase{
```

2023-12-11 17:48 UTC, skriss requested changes
Couple nits but otherwise looks pretty good to me (I'm heavily relying on the tests here for correctness!)

2023-12-11 17:48 UTC, skriss commented on examples/example-workload/gatewayapi/blue-green/blue-green.yaml
> +      weight: 90
Let's drop this file's change from this PR, looks inadvertent.

2023-12-11 17:48 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +		// (c) pass the all check for it
I'm not sure what this (c) means - could you be more specific?

2023-12-11 17:48 UTC, skriss commented on internal/dag/gatewayapi_processor.go
> +) (info *listenerInfo) {
We prefer not to use named return params, let's switch this to non-named and just return the local variable where needed.

2023-12-12 15:04 UTC, skriss approved these changes
LGTM, will leave for @sunjayBhatia

2023-12-12 17:50 UTC, sunjayBhatia approved these changes

2023-12-12 17:50 UTC, merged