feat: add max-connections-per-listener config option
projectcontour/contour pull request #6058
Opened 2024-01-06 01:02 UTC by flawedmatrix

Adds a setting for `max-connections-per-listener` to limit the number of active connections to a listener.

fixes #5654

2024-01-08 21:10 UTC, sunjayBhatia commented
breadcrumb to think about when I get a chance to do a full review: think about admin/stats/etc. Listeners

2024-01-09 18:23 UTC, sunjayBhatia commented
> breadcrumb to think about when I get a chance to do a full review: think about admin/stats/etc. Listeners

so far my thought is to exclude those Listeners from this change since the shouldn't be at as much risk from a DOS attack (should not be exposed outside of the cluster, or even node), but we could do a follow on to set a reasonable default number of max connections for these listeners (or even make the limit configurable)

If we do want to ever set the global connection limit, that applies to all Listeners including the admin one, stats, etc., so we would have to make sure those don't get starved, and maybe set the "ignore global limit" flag for them

2024-01-09 18:52 UTC, skriss requested changes
One little changelog nit, otherwise LGTM. I agree with @sunjayBhatia that it should be fine to not apply this setting to the admin/stats listeners.

2024-01-09 18:52 UTC, skriss commented on changelogs/unreleased/6058-flawedmatrix-minor.md
> +Adds a `max-connections-per-listener` config option to limit the number of active connections to a listener. The default, if unset, is unlimited.
It'd be nice to spell out the full YAML path of the config option for both the ContourConfiguration CRD (e.g. `spec.envoy.listener.maxConnectionsPerListener`) and the Contour config file (`listener.max-connections-per-listener`) here for clarity.

2024-01-09 19:58 UTC, flawedmatrix commented
Yeah, that makes sense. If we ever need to set a listener connection limit on the admin and stats endpoint that can be a follow-on change.

2024-01-09 20:50 UTC, skriss approved these changes
LGTM, will leave for @sunjayBhatia to review as well. Thanks @flawedmatrix and @christianang!

2024-01-10 16:00 UTC, sunjayBhatia approved these changes

2024-01-10 16:06 UTC, merged