[WIP]Add support for disabled-features in provisioner
projectcontour/contour pull request #6152
Opened 2024-02-02 02:41 UTC by lubronzhan

Based on previous art from @padlar https://github.com/projectcontour/contour/pull/5331.

This PR introduce support for disabled-features in provisioner so that any Contour instances associated with this ContourDeployment with disabled-features flag will stop reconciling CRDs defined inside.

Right now supported values are: `grpcroutes;tlsroutes;extensionservices;backendtlspolicies`

TODO:
[] Add e2e test

2024-02-03 05:14 UTC, lubronzhan commented on internal/provisioner/model/model.go
>  	WatchNamespaces []string
Will change this to original v1.Namespace type in a follow up PR.
I think it make more sense to keep model and types consistent, and put conversion function inside model

2024-02-07 23:02 UTC, sunjayBhatia reviewed
just a few comments for now, will do another pass shortly

2024-02-07 23:02 UTC, sunjayBhatia commented on internal/provisioner/objects/deployment/deployment_test.go
> +			disabledFeatures: []contour_v1.Feature{"ns1", "ns2"},
nit: use a feature name here just for readability (functionally doesnt matter and could by any string, but just for someone reading it later)

2024-02-07 23:02 UTC, sunjayBhatia commented on test/e2e/provisioner/provisioner_test.go
> +	"k8s.io/utils/ptr"
can do in a later issue of course cc @projectcontour/maintainers

2024-02-08 06:04 UTC, lubronzhan commented on test/e2e/provisioner/provisioner_test.go
> +	"k8s.io/utils/ptr"
Cool, let me create a Jira for that and I can work on it as well

2024-02-08 06:06 UTC, lubronzhan commented on internal/provisioner/model/model.go
>  	WatchNamespaces []string
Cool let me change it here

2024-02-08 18:15 UTC, lubronzhan commented
The upgrade test has many
>2024/02/08 08:34:22.321719 error making request #79: Get "http://172.18.255.200/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
Is that related to something known issue

2024-02-08 20:55 UTC, sunjayBhatia approved these changes
I'll wait to merge in case anyone else wants a look but LGTM

2024-02-09 17:41 UTC, skriss requested changes
Just one docs nit, otherwise LGTM

@sunjayBhatia I'd be fine getting this in for the upcoming release, WDYT?

2024-02-09 17:41 UTC, skriss commented on apis/projectcontour/v1alpha1/contourdeployment.go
> +	// DisabledFeatures defines an array of Gateway API CRDs that will be ignored by
Technically they are not all Gateway API resources (`extensionservices` is a Contour resource):
```suggestion
	// DisabledFeatures defines an array of resources that will be ignored by
```

2024-02-09 17:52 UTC, sunjayBhatia commented
> The upgrade test has many context deadline exceeded issue, is that related to something known issue
> 
> > 2024/02/08 08:34:22.321719 error making request #79: Get "http://172.18.255.200/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> 
> Didn't find the button to rerun the test

yeah, 

> Just one docs nit, otherwise LGTM
> 
> @sunjayBhatia I'd be fine getting this in for the upcoming release, WDYT?

yep sounds good to me 👍🏽

2024-02-09 17:58 UTC, skriss commented
> > The upgrade test has many context deadline exceeded issue, is that related to something known issue
> > > 2024/02/08 08:34:22.321719 error making request #79: Get "http://172.18.255.200/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
> > 
> > 
> > Didn't find the button to rerun the test
> 
> yeah, I dont think we made an issue for it but we've seen this a lot I believe since we haven't properly coordinated the Envoy/Contour Service/Deployment redeploy order in the provisioner

ref. https://github.com/projectcontour/contour/issues/5375, got closed as stale but still valid to do

2024-02-09 20:29 UTC, skriss approved these changes

2024-02-09 20:29 UTC, merged