contour: adds global ext auth support to fallback certificates
projectcontour/contour pull request #6558
Opened 2024-07-16 18:59 UTC by erikflores7

When using IP to connect, no SNI is sent so the Fallback certificate has to be used in these cases. But when using Fallback certificate, there is currently no support for auth. This change adds the auth filter to add support for the fallback certificate.

 Fixes #6512 
 
 
  Signed-off-by: Erik Flores eflores@anduril.com

2024-07-16 23:21 UTC, skriss requested changes
Thanks for the PR! Code change LGTM, just need to add a test case. You'll also need to make sure all of your commits have DCO signoff.

2024-07-16 23:21 UTC, skriss commented on internal/xdscache/v3/listener.go
> +					AddFilter(authzFilter).
Let's add a test case for this; I think https://github.com/projectcontour/contour/blob/main/internal/featuretests/v3/global_authorization_test.go would be the best place to do this.

2024-07-25 16:03 UTC, skriss approved these changes
Thanks @erikflores7, LGTM!

2024-07-25 16:04 UTC, skriss commented on changelogs/unreleased/6558-eflores-minor.md
> +## Fallback Certificate: Add Global Ext Auth support
Looks like this file should be renamed to `6558-erikflores-minor.md` to pass the CI check but we can merge as-is and fix later/for release notes.

2024-07-25 16:07 UTC, skriss commented on internal/featuretests/v3/global_authorization_test.go
> +	"k8s.io/apimachinery/pkg/types"
Please run `make format` to move this import to the expected section and fix the linter error.

2024-07-25 17:09 UTC, erikflores7 commented
Thank you for the quick reviews!

By the way, would you happen to know what the lift is to get this added at the HTTPProxy level? There's a comment about the different connection managers: https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L280-L290

I have to look into this more, but I _believe_ when using the Global Ext Auth that the auth check fires before an HTTP -> HTTPS redirect happens where as when setting auth at proxy level that doesn't seem to be an issue

2024-07-25 19:21 UTC, skriss commented
> By the way, would you happen to know what the lift is to get this added at the HTTPProxy level? There's a comment about the different connection managers: https://github.com/projectcontour/contour/blob/main/internal/dag/httpproxy_processor.go#L280-L290
> 
> I have to look into this more, but I _believe_ when using the Global Ext Auth that the auth check fires before an HTTP -> HTTPS redirect happens where as when setting auth at proxy level that doesn't seem to be an issue

Just to clarify, the use case that isn't working for you is when global ExtAuthz is enabled, and you have TLS-enabled HTTPProxies, and insecure HTTP requests being made to them? Because I would expect global ext auth to already work correctly for both (a) HTTPProxies without TLS (this was what the feature was originally implemented for), and (b) HTTPProxies with TLS, and requests made over HTTPS/TLS.

2024-07-25 19:23 UTC, merged