Clarified how XFCC headers are handled
projectcontour/contour pull request #6586
Opened 2024-07-29 06:13 UTC by jroper

Since XFCC headers contain authentication information, it's important for users to know precisely how Contour (ie Envoy) handles existing XFCC headers from clients - ie, are they blocked, or appended to, and if blocked, in what circumstances are they blocked? Getting this wrong could allow serious vulnerabilities such as spoofing TLS client authentication via the XFCC header.

This documents Contours precise behaviour, so that users can know exactly how they are required to handle that header without needing to dive into the Contour source code.

My understanding from reading the [Contour source code](https://github.com/gautierdelorme/contour/blob/main/internal/envoy/v3/listener.go#L483), as well as the [Envoy documentation](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-enum-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-forwardclientcertdetails), is that when forwarding client certificate details is not configured in Contour, Contour leaves `ForwardClientCertDetails` in Envoy unset, which means it defaults to `SANITIZE`, which means incoming headers from clients are blocked. Meanwhile, when forwarding client certificate details is configured in Contour, Contour sets `ForwardClientCertDetails` to `SANITIZE_SET` in Envoy, which means incoming XFCC headers are blocked, and if an incoming cert is present, a new XFCC header is added.

2024-08-01 14:42 UTC, tsaarni requested changes
Good point, the change looks good to me! 

Could you add DCO / signed-off-by line to the commit https://github.com/projectcontour/contour/blob/main/CONTRIBUTING.md#commit-message-and-pr-guidelines

2024-08-05 11:46 UTC, jroper commented
Done.

2024-08-14 06:05 UTC, tsaarni approved these changes

2024-08-14 06:05 UTC, merged

2024-08-14 06:06 UTC, tsaarni commented
Thank you @jroper!