Update HTTPRequestRedirectPolicy StatusCode to use RedirectResponseCode
projectcontour/contour pull request #6789
Opened 2024-11-26 04:52 UTC by billyjs

To fix #6788 

Allow 303, 307, 308 response status codes when using the request redirect policy.

2024-11-26 05:07 UTC, tsaarni commented
Hi @billyjs! You can run`make generate` and commit the outcome to fix the build error and please also add one-liner changelog entry `changelogs/unreleased/6789-billyjs-small.md`.

2024-11-26 05:48 UTC, billyjs commented
@tsaarni what is the release cadence for this project?

2024-11-26 06:41 UTC, tsaarni commented
>  what is the release cadence for this project?

Generally, we have aimed for [quarterly releases](https://projectcontour.io/resources/support/) but that schedule hasn't always been strictly followed.

By the way, I noticed there's a minor issue (#6791) that needs to be resolved before moving forward with this PR

2024-11-28 05:17 UTC, billyjs commented
@tsaarni I used your changes in #6791 to generate the deepcopy file and updated the types in the tests. I think it should pass the CI tests now as it passes the tests locally.

2024-12-16 03:30 UTC, billyjs commented
Anything else required to get this PR merged?

2025-01-08 14:48 UTC, tsaarni requested changes
Thank you @billyjs, looks good to me. but just one small request inline for the changelog entry so that users will better chance finding this improvement!

2025-01-08 14:48 UTC, tsaarni commented on changelogs/unreleased/6789-billyjs-small.md
> +Use RedirectResponseCode instead of just 301/302 for HTTPRequestRedirectPolicy StatusCode
```suggestion
`HTTPProxy.spec.routes.requestRedirectPolicy.statusCode` now supports 303, 307 and 308 redirect status codes in addition to 301 and 302.
```

2025-02-06 14:49 UTC, merged